### ISSUE TITLE
Rewrite Quotes data models: use ToModel/FromModel/Patch pattern

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-quote#2]
Look at Catalog module, for example.

**Comment by artem-dudarev** [comment]
I would use ToDomainModel and FromDomainModel names because just Model is not obvious.

**Comment by asvishnyakov** [comment]
@artem-dudarev I think it's bad place to propose changes. If you don't like this names and want to clarify them, ask @tatarincev to change it on platform to .NET Core migration process ;)

**Comment by artem-dudarev** [comment]
@asvishnyakov It's not related to .NET Core migration process. It's about more readable code.

**Comment by tatarincev** [comment]
I disagree with @artem-dudarev  because  use  this kind of naming will break  integrity of application architecture

**Comment by kostyrin** [comment]
1. read best practices, like https://www.toptal.com/qa/how-to-write-testable-code-and-why-it-matters
2. The unittests should be easy readable without looking inside, ex.: MethodName_ReturnTheResult() or MethodName_Scenario_Result(), look at https://github.com/VirtoCommerce/vc-platform-core/tree/feature/notifications/Modules/vc-module-notifications/VirtoCommerce.NotificationsModule.Tests/UnitTests
3. And each methods must nave three parts //Arrange, //Act, //Assert

**Comment by kostyrin** [comment]
and read this https://stackify.com/unit-testing-basics-best-practices/

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
