### ISSUE TITLE
Blade.error should not be null

### ISSUE THREAD

**Issue by MalikJuly** [VirtoCommerce/vc-module-quote#4]
As part of the vc-module-quote, two scripts (quote-detail.js, quote-assets) define the variable blade.error as null, which causes errors when trying to create new Attachments and Assets in this module. You can solve this problem in 2 ways: modify the scripts in the vc-module-quote or add an error == null check in the vc-platform bladeNavigation.js script. Preferably, in my view, the second option, because the same situation can be repeated in other modules.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
