### ISSUE TITLE
Swagger document build error

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-quote#8]
When getting Quote module swagger doc using [/docs/VirtoCommerce.Quote/v1](https://admin-demo.virtocommerce.com/docs/VirtoCommerce.Quote/v1), we are getting following error because of duplicated type names:
`{"message":"An error has occurred.","exceptionMessage":"Conflicting schemaIds: Duplicate schemaIds detected for types VirtoCommerce.Domain.Commerce.Model.Address and VirtoCommerce.QuoteModule.Web.Model.Address. See the config setting - \"UseFullTypeNameInSchemaIds\" for a potential workaround","exceptionType":"System.InvalidOperationException"`

Need to add 
`		<useFullTypeNameInSwagger>true</useFullTypeNameInSwagger>
`
to module manifest to solve the problem.

**Comment by collinstevens** [comment]
Is there any plan to resolve this..? Still can't generate an updated AutoRest client.

**Comment by yecli** [comment]
The fix is merged to DEV branch, you can use it.
Having problems with publishing release, it will take some time.

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-quote/releases/tag/v2.13.0
